from __future__ import annotations

"""
ProjectPlanner — use an LLM to generate a complete project file tree.

The planner returns a structured dict that other modules (CodeGenerator,
DependencyInstaller, …) consume directly.  All heavy content (file bodies,
component JSX, etc.) is generated by the LLM; the planner only directs the
prompt and parses the response.
"""

import json
import logging
import re
import textwrap
from typing import Any

from api.services.openai_client import openai_client

logger = logging.getLogger(__name__)


def _strip_code_fences(text: str) -> str:
    """Remove markdown code fences that LLMs sometimes wrap output in."""
    text = text.strip()
    text = re.sub(r"^```[a-zA-Z]*\n?", "", text)
    text = re.sub(r"\n?```\s*$", "", text)
    return text.strip()


# Packages that are always installed in a vite-react-tailwind project
_SAFE_PACKAGES = frozenset({"react", "react-dom"})

def _validate_app_tsx(code: str, is_next: bool) -> str | None:
    """Validate LLM-generated App.tsx. Returns the code if valid, None to trigger fallback.

    Rejects:
    - Next.js imports in a Vite project
    - Any npm package imports other than react/react-dom (they're not installed)
    - Local relative imports other than ./components/* and ./data/*
    """
    if not code or len(code) < 50:
        return None

    # Reject if HTML `class=` attribute is used instead of JSX `className=`
    if re.search(r'\bclass\s*=\s*["\']', code):
        logger.warning("[PROJECT_PLANNER] rejected App.tsx: HTML class= attribute (use className=)")
        return None

    for line in code.splitlines():
        line = line.strip()
        if not line.startswith("import "):
            continue
        # Extract 'from "..."' or "from '...'"
        m = re.search(r"""from\s+['"]([^'"]+)['"]""", line)
        if not m:
            continue
        pkg = m.group(1)

        # Next.js check (Vite projects only)
        if not is_next and pkg.startswith("next/"):
            logger.warning("[PROJECT_PLANNER] rejected App.tsx: next/* import in Vite project")
            return None

        # Local relative imports: only allow ./components/* and ./data/*
        if pkg.startswith("./") or pkg.startswith("../"):
            allowed_local = ("./components/", "./data/")
            if not any(pkg.startswith(p) for p in allowed_local):
                logger.warning("[PROJECT_PLANNER] rejected App.tsx: disallowed local import %r", pkg)
                return None
            continue

        # npm package — only safe ones allowed
        root_pkg = pkg.split("/")[0]
        if root_pkg not in _SAFE_PACKAGES:
            logger.warning("[PROJECT_PLANNER] rejected App.tsx: uninstalled package %r", pkg)
            return None

    # Reject if the file has no h1 or h2 (visual reviewer requires them)
    if not re.search(r'<h[12][\s>]', code):
        logger.warning("[PROJECT_PLANNER] rejected App.tsx: no h1/h2 heading found")
        return None

    return code


# ── Canned templates (used when LLM is unavailable) ──────────────────────────

_TAILWIND_CONFIG = """\
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
}
"""

_VITE_CONFIG = """\
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
"""

_INDEX_HTML = """\
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Xyron App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
"""

_MAIN_TSX = """\
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
"""

_INDEX_CSS = """\
@tailwind base;
@tailwind components;
@tailwind utilities;

* { box-sizing: border-box; margin: 0; padding: 0; }
"""

_TSCONFIG = json.dumps(
    {
        "compilerOptions": {
            "target": "ES2020",
            "useDefineForClassFields": True,
            "lib": ["ES2020", "DOM", "DOM.Iterable"],
            "module": "ESNext",
            "skipLibCheck": True,
            "moduleResolution": "bundler",
            "allowImportingTsExtensions": True,
            "resolveJsonModule": True,
            "isolatedModules": True,
            "noEmit": True,
            "jsx": "react-jsx",
            "strict": True,
            "noUnusedLocals": True,
            "noUnusedParameters": True,
            "noFallthroughCasesInSwitch": True,
        },
        "include": ["src"],
        "references": [{"path": "./tsconfig.node.json"}],
    },
    indent=2,
)

_TSCONFIG_NODE = json.dumps(
    {
        "compilerOptions": {
            "composite": True,
            "skipLibCheck": True,
            "module": "ESNext",
            "moduleResolution": "bundler",
            "allowSyntheticDefaultImports": True,
        },
        "include": ["vite.config.ts"],
    },
    indent=2,
)


class ProjectPlanner:
    """Generate a full project blueprint using an LLM."""

    # ── Public entry point ─────────────────────────────────────────────────────

    async def plan(self, goal: str, stack: str, design_brief: str | None = None) -> dict[str, Any]:
        """Return a project blueprint dict.

        Schema::

            {
              "name": "clothing-website",
              "description": "...",
              "files": [{"path": "src/App.tsx", "content": "..."}],
              "dependencies": ["react", "react-dom"],
              "dev_dependencies": ["vite", "@vitejs/plugin-react", "tailwindcss", ...],
              "scripts": {"dev": "vite", "build": "vite build", "preview": "vite preview"},
              "commands_after_install": ["npx tailwindcss init -p"]
            }

        *design_brief* — optional design intelligence string from DesignResearcher.
        When provided it is injected into the code-generation prompt so the
        generated UI follows current design trends for the project category.
        """
        if stack == "vite-react-tailwind":
            return await self._plan_vite_react(goal, design_brief=design_brief)
        if stack == "nextjs":
            return await self._plan_nextjs(goal, design_brief=design_brief)
        if stack == "python-flask":
            return await self._plan_flask(goal)
        if stack == "html-vanilla":
            return await self._plan_vanilla(goal)
        # Default fallback
        return await self._plan_vite_react(goal, design_brief=design_brief)

    # ── Stack-specific planners ────────────────────────────────────────────────

    async def _plan_vite_react(self, goal: str, design_brief: str | None = None) -> dict[str, Any]:
        """Generate a Vite + React + Tailwind project."""
        project_name = self._slugify(goal)
        app_tsx = await self._generate_app_tsx(goal, "vite-react-tailwind", design_brief=design_brief)

        base_plan: dict[str, Any] = {
            "name": project_name,
            "description": goal,
            "dependencies": ["react", "react-dom"],
            "dev_dependencies": [
                "vite",
                "@vitejs/plugin-react",
                "tailwindcss",
                "postcss",
                "autoprefixer",
                "typescript",
                "@types/react",
                "@types/react-dom",
            ],
            "scripts": {
                "dev": "vite",
                "build": "tsc && vite build",
                "preview": "vite preview",
                "lint": "tsc --noEmit",
            },
            "commands_after_install": [],
            "files": [
                {"path": "index.html", "content": _INDEX_HTML},
                {"path": "vite.config.ts", "content": _VITE_CONFIG},
                {"path": "tailwind.config.js", "content": _TAILWIND_CONFIG},
                {"path": "tsconfig.json", "content": _TSCONFIG},
                {"path": "tsconfig.node.json", "content": _TSCONFIG_NODE},
                {"path": "src/main.tsx", "content": _MAIN_TSX},
                {"path": "src/index.css", "content": _INDEX_CSS},
                {"path": "src/App.tsx", "content": app_tsx},
            ],
        }

        # Inject package.json
        base_plan["files"].append(
            {
                "path": "package.json",
                "content": self._make_package_json(
                    project_name,
                    base_plan["dependencies"],
                    base_plan["dev_dependencies"],
                    base_plan["scripts"],
                ),
            }
        )

        # PostCSS config for Tailwind v3 (v4 removed the direct PostCSS plugin)
        base_plan["files"].append(
            {
                "path": "postcss.config.js",
                "content": (
                    "export default {\n"
                    "  plugins: {\n"
                    "    tailwindcss: {},\n"
                    "    autoprefixer: {},\n"
                    "  },\n"
                    "};\n"
                ),
            }
        )

        return base_plan

    async def _plan_nextjs(self, goal: str, design_brief: str | None = None) -> dict[str, Any]:
        """Generate a minimal Next.js 14 App Router project."""
        project_name = self._slugify(goal)
        page_tsx = await self._generate_app_tsx(goal, "nextjs", design_brief=design_brief)

        files = [
            {
                "path": "package.json",
                "content": json.dumps(
                    {
                        "name": project_name,
                        "version": "0.1.0",
                        "private": True,
                        "scripts": {
                            "dev": "next dev",
                            "build": "next build",
                            "start": "next start",
                        },
                        "dependencies": {
                            "next": "14.2.3",
                            "react": "^18",
                            "react-dom": "^18",
                        },
                        "devDependencies": {
                            "typescript": "^5",
                            "@types/node": "^20",
                            "@types/react": "^18",
                            "@types/react-dom": "^18",
                            "tailwindcss": "^3",
                            "autoprefixer": "^10",
                            "postcss": "^8",
                        },
                    },
                    indent=2,
                ),
            },
            {
                "path": "app/page.tsx",
                "content": page_tsx,
            },
            {
                "path": "app/layout.tsx",
                "content": textwrap.dedent(
                    """\
                    import type { Metadata } from 'next'
                    import './globals.css'

                    export const metadata: Metadata = {
                      title: 'Xyron App',
                      description: 'Generated by Xyron Coding Agent',
                    }

                    export default function RootLayout({ children }: { children: React.ReactNode }) {
                      return (
                        <html lang="en">
                          <body>{children}</body>
                        </html>
                      )
                    }
                    """
                ),
            },
            {"path": "app/globals.css", "content": _INDEX_CSS},
            {"path": "tailwind.config.js", "content": _TAILWIND_CONFIG},
            {"path": "postcss.config.js", "content": "export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n"},
        ]

        return {
            "name": project_name,
            "description": goal,
            "dependencies": ["next", "react", "react-dom"],
            "dev_dependencies": ["typescript", "@types/react", "@types/react-dom", "tailwindcss", "autoprefixer", "postcss"],
            "scripts": {"dev": "next dev", "build": "next build", "start": "next start"},
            "commands_after_install": [],
            "files": files,
        }

    async def _plan_flask(self, goal: str) -> dict[str, Any]:
        """Generate a minimal Python Flask project."""
        project_name = self._slugify(goal)
        app_py = await self._generate_flask_app(goal)

        files = [
            {"path": "app.py", "content": app_py},
            {
                "path": "requirements.txt",
                "content": "flask>=3.0\nflask-cors\n",
            },
            {
                "path": "templates/index.html",
                "content": textwrap.dedent(
                    """\
                    <!DOCTYPE html>
                    <html lang="en">
                    <head><meta charset="UTF-8"><title>Flask App</title></head>
                    <body>
                      <h1>Flask App — Xyron Generated</h1>
                    </body>
                    </html>
                    """
                ),
            },
        ]

        return {
            "name": project_name,
            "description": goal,
            "dependencies": [],
            "dev_dependencies": [],
            "scripts": {},
            "commands_after_install": [],
            "files": files,
            "python_requirements": ["flask>=3.0", "flask-cors"],
        }

    async def _plan_vanilla(self, goal: str) -> dict[str, Any]:
        """Generate a minimal plain HTML/CSS/JS project."""
        project_name = self._slugify(goal)
        html = await self._generate_html_page(goal)

        return {
            "name": project_name,
            "description": goal,
            "dependencies": [],
            "dev_dependencies": ["serve"],
            "scripts": {"dev": "npx serve .", "start": "npx serve ."},
            "commands_after_install": [],
            "files": [
                {"path": "index.html", "content": html},
                {
                    "path": "style.css",
                    "content": "* { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: sans-serif; }\n",
                },
                {"path": "main.js", "content": "// Xyron generated\nconsole.log('App ready');\n"},
                {
                    "path": "package.json",
                    "content": json.dumps(
                        {
                            "name": project_name,
                            "version": "0.1.0",
                            "scripts": {"dev": "npx serve .", "start": "npx serve ."},
                            "devDependencies": {"serve": "^14"},
                        },
                        indent=2,
                    ),
                },
            ],
        }

    # ── LLM content generators ─────────────────────────────────────────────────

    async def _generate_app_tsx(self, goal: str, stack: str, design_brief: str | None = None) -> str:
        """Generate the main App.tsx (or page.tsx) with rich, styled content."""
        is_next = stack == "nextjs"
        directive = '"use client"\n\n' if is_next else ""

        design_section = (
            f"\nDesign brief (follow this closely):\n{design_brief}\n"
            if design_brief else ""
        )

        framework_note = (
            "This is a Next.js component — use Next.js imports where appropriate."
            if is_next else
            "VITE + React project. ONLY ALLOWED IMPORT: 'react'. Nothing else — no react-router-dom, no react-redux, no next/*, no axios, no lodash."
        )

        system_prompt = textwrap.dedent(
            f"""\
            You are an expert React/TypeScript developer writing a single-file Vite component.
            Generate a complete, visually stunning React component for:
            "{goal}"
            {design_section}
            ABSOLUTE RULES — any violation makes the file fail to compile:
            1. {framework_note}
            2. Return ONLY raw TypeScript/TSX. The first word must be "import".
            3. NO markdown fences (no ```).  NO explanations.
            4. The ONLY import allowed is: import React, {{ useState }} from 'react'
            5. ALL data (products, features, items) must be const arrays INSIDE this file.
            6. Include: <header> with <nav>, a <main> section with className="hero" containing <h1> and <h2>, a products/features section, and <footer>.
            7. Use Tailwind CSS classes for all styling.
            8. export default App as the last line.
            """
        )

        try:
            result = openai_client.generate(
                [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Generate App.tsx for: {goal}"},
                ],
                model="gpt-4o-mini",
                max_tokens=1800,
            )
            if result:
                result = _strip_code_fences(result)
                result = _validate_app_tsx(result, is_next)
            if result:
                return directive + result
        except Exception as exc:
            logger.warning("[PROJECT_PLANNER] LLM App.tsx generation failed: %s", exc)

        # Fallback — guaranteed to compile and pass visual reviewer checks
        logger.info("[PROJECT_PLANNER] using fallback App.tsx (LLM output rejected or unavailable)")
        return directive + self._fallback_app_tsx(goal)

    async def _generate_flask_app(self, goal: str) -> str:
        """Generate app.py content for a Flask project."""
        system_prompt = (
            "You are a Python Flask developer. Generate a complete app.py for:\n"
            f'"{goal}"\n\n'
            "Requirements:\n"
            "- Use Flask 3.x syntax.\n"
            "- Include at least one API route and one HTML template route.\n"
            "- Use flask_cors for CORS support.\n"
            "- Debug mode controlled by an environment variable.\n"
            "- Return ONLY the Python source code, no markdown."
        )
        try:
            result = openai_client.generate(
                [{"role": "system", "content": system_prompt}],
                model="gpt-4o-mini",
            )
            if result:
                return result
        except Exception as exc:
            logger.warning("[PROJECT_PLANNER] Flask app.py generation failed: %s", exc)

        return textwrap.dedent(
            f"""\
            from flask import Flask, render_template, jsonify
            from flask_cors import CORS
            import os

            app = Flask(__name__)
            CORS(app)

            @app.route('/')
            def index():
                return render_template('index.html')

            @app.route('/api/health')
            def health():
                return jsonify({{"status": "ok", "app": "{goal}"}})

            if __name__ == '__main__':
                debug = os.environ.get('FLASK_DEBUG', '1') == '1'
                app.run(host='0.0.0.0', port=5000, debug=debug)
            """
        )

    async def _generate_html_page(self, goal: str) -> str:
        """Generate a styled index.html for a vanilla project."""
        try:
            result = openai_client.generate(
                [
                    {
                        "role": "system",
                        "content": (
                            "Generate a complete, styled, single-page HTML file for:\n"
                            f'"{goal}"\n'
                            "Use modern CSS (flexbox, grid, CSS custom properties).\n"
                            "No frameworks — pure HTML/CSS/JS.\n"
                            "Return ONLY the HTML file, no markdown."
                        ),
                    }
                ],
                model="gpt-4o-mini",
            )
            if result:
                return result
        except Exception as exc:
            logger.warning("[PROJECT_PLANNER] vanilla HTML generation failed: %s", exc)

        return textwrap.dedent(
            f"""\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>{goal}</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
              <header><h1>{goal}</h1></header>
              <main><p>Xyron generated project.</p></main>
              <script src="main.js"></script>
            </body>
            </html>
            """
        )

    # ── Fallback templates ─────────────────────────────────────────────────────

    @staticmethod
    def _fallback_app_tsx(goal: str) -> str:
        return textwrap.dedent(
            f"""\
            import React from 'react'

            const App: React.FC = () => {{
              return (
                <div className="min-h-screen bg-gray-50">
                  <header>
                    <nav className="bg-white shadow-sm px-6 py-4 flex items-center justify-between">
                      <span className="text-xl font-bold text-indigo-600">Xyron App</span>
                      <div className="flex gap-6 text-sm text-gray-600">
                        <a href="#" className="hover:text-indigo-600">Home</a>
                        <a href="#" className="hover:text-indigo-600">About</a>
                        <a href="#" className="hover:text-indigo-600">Contact</a>
                      </div>
                    </nav>
                  </header>

                  <main>
                    <section className="hero flex flex-col items-center justify-center py-24 px-4 text-center bg-gradient-to-br from-indigo-50 to-white">
                      <h1 className="text-5xl font-extrabold text-gray-900 mb-4">
                        {goal}
                      </h1>
                      <h2 className="text-xl text-gray-500 mb-8 max-w-xl">
                        Built with Vite, React, and Tailwind CSS by the Xyron Coding Agent.
                      </h2>
                      <button className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold px-8 py-3 rounded-xl transition">
                        Get Started
                      </button>
                    </section>

                    <section className="py-16 px-6 max-w-6xl mx-auto">
                      <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">Features</h2>
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                        {{['Quality', 'Speed', 'Style'].map((f) => (
                          <div key={{f}} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                            <h3 className="font-semibold text-lg mb-2">{{f}}</h3>
                            <p className="text-gray-500 text-sm">Premium {{f.toLowerCase()}} crafted for you.</p>
                          </div>
                        ))}}
                      </div>
                    </section>
                  </main>

                  <footer className="text-center text-sm text-gray-400 py-6 border-t border-gray-100">
                    © {{new Date().getFullYear()}} Xyron. All rights reserved.
                  </footer>
                </div>
              )
            }}

            export default App
            """
        )

    # ── Utilities ─────────────────────────────────────────────────────────────

    @staticmethod
    def _slugify(text: str) -> str:
        """Convert goal text to a safe project name."""
        cleaned = re.sub(
            r"^(build|create|make|generate|design|write|develop|set up|setup)(\s+me)?\s+(an?\s+)?",
            "",
            text.strip(),
            flags=re.IGNORECASE,
        )
        cleaned = cleaned.lower()
        cleaned = re.sub(r"[^a-z0-9]+", "-", cleaned)
        cleaned = re.sub(r"-{2,}", "-", cleaned).strip("-")
        return cleaned[:50] or "my-project"

    # Pin versions for packages where "latest" breaks the generated template.
    # tailwindcss v4 removed the direct PostCSS plugin — our template uses v3 syntax.
    _DEV_VERSION_PINS: dict[str, str] = {
        "tailwindcss":  "^3.4.0",
        "autoprefixer": "^10.4.0",
        "postcss":      "^8.4.0",
    }

    @staticmethod
    def _make_package_json(
        name: str,
        deps: list[str],
        dev_deps: list[str],
        scripts: dict[str, str],
    ) -> str:
        pkg = {
            "name": name,
            "version": "0.1.0",
            "private": True,
            "type": "module",
            "scripts": scripts,
            "dependencies": {d: "latest" for d in deps},
            "devDependencies": {
                d: ProjectPlanner._DEV_VERSION_PINS.get(d, "latest")
                for d in dev_deps
            },
        }
        return json.dumps(pkg, indent=2)
