from __future__ import annotations

"""
CleanupReporter — generate human-readable cleanup reports.

Reports are saved to ~/.xyron/reports/cleanup_<timestamp>.md
Also provides a short voice-friendly summary string for TTS.

Log tags: [CLEANER_REPORT_CREATED]
"""

import logging
import time
from pathlib import Path
from typing import Optional

try:
    import humanize as _humanize
    _HAS_HUMANIZE = True
except ImportError:
    _HAS_HUMANIZE = False

from api.agents.agent_types import AgentTask

logger = logging.getLogger("api.agents.automation_agent.cleanup_reporter")


def _naturalsize(n: int) -> str:
    if _HAS_HUMANIZE:
        return _humanize.naturalsize(n, binary=True)
    for unit in ("B", "KiB", "MiB", "GiB"):
        if n < 1024:
            return f"{n:.1f} {unit}"
        n //= 1024  # type: ignore[assignment]
    return f"{n:.1f} GiB"


class CleanupReporter:
    """Generate and persist cleanup reports."""

    REPORTS_DIR: Path = Path.home() / ".xyron" / "reports"

    # ── Report generation ─────────────────────────────────────────────────────

    async def generate_report(self, results: dict, task: AgentTask) -> str:
        """
        Generate a Markdown cleanup report and save to REPORTS_DIR.

        Expected results dict:
        {
            "scanned_bytes": int,
            "freed_bytes":   int,
            "files_removed": int,
            "categories":    dict,   # category → {size, count, ...}
        }

        Returns the full report text.
        """
        ts = int(time.time())
        ts_human = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(ts))

        scanned = results.get("scanned_bytes", 0)
        freed = results.get("freed_bytes", 0)
        removed = results.get("files_removed", 0)
        categories = results.get("categories", {})

        lines: list[str] = [
            "# Xyron Cleanup Report",
            "",
            f"**Date:** {ts_human}",
            f"**Task ID:** `{task.task_id}`",
            f"**Goal:** {task.goal}",
            "",
            "## Summary",
            "",
            f"| Metric        | Value                    |",
            f"|---------------|--------------------------|",
            f"| Scanned       | {_naturalsize(scanned):>24} |",
            f"| Freed         | {_naturalsize(freed):>24} |",
            f"| Files removed | {removed:>24,} |",
            "",
        ]

        if categories:
            lines.append("## Breakdown by Category")
            lines.append("")
            lines.append("| Category | Size | Files |")
            lines.append("|----------|------|-------|")
            for cat, data in categories.items():
                if isinstance(data, dict):
                    size = data.get("size", 0) or data.get("freed_bytes", 0)
                    count = data.get("count", 0) or data.get("files_removed", 0)
                elif isinstance(data, (int, float)):
                    size = int(data)
                    count = 0
                else:
                    continue
                lines.append(f"| {cat} | {_naturalsize(size)} | {count:,} |")
            lines.append("")

        lines += [
            "---",
            "_Generated by Xyron Automation Agent (Phase 3.3)_",
        ]

        report_text = "\n".join(lines)
        saved_path = self._save_report(report_text, ts)
        if saved_path:
            logger.info("[CLEANER_REPORT_CREATED] path=%s", saved_path)

        return report_text

    def _save_report(self, content: str, ts: int) -> Optional[Path]:
        """Write report to disk. Returns path on success, None on failure."""
        try:
            self.REPORTS_DIR.mkdir(parents=True, exist_ok=True)
            path = self.REPORTS_DIR / f"cleanup_{ts}.md"
            path.write_text(content, encoding="utf-8")
            return path
        except Exception as exc:
            logger.warning("[CLEANUP_REPORTER] save failed: %r", exc)
            return None

    # ── Voice summary ─────────────────────────────────────────────────────────

    def format_voice_summary(self, results: dict) -> str:
        """
        Short TTS-friendly summary.
        Example: 'I freed 2.8 GiB by removing 1,247 temp files.'
        """
        freed = results.get("freed_bytes", 0)
        removed = results.get("files_removed", 0)

        if freed == 0 and removed == 0:
            return "Cleanup complete. No files were removed."

        parts: list[str] = []
        if freed > 0:
            parts.append(f"freed {_naturalsize(freed)}")
        if removed > 0:
            parts.append(f"removed {removed:,} files")

        body = " and ".join(parts)
        return f"I {body}."
